### ISSUE TITLE
Ratgdo random door open events. (MQTT, S+ 1.0)

### ISSUE THREAD

**Issue by preppietechie** [ratgdo/mqtt-ratgdo#34]
About half a dozen times now RatGDO will randomly open the garage door. Checking the logs in HomeAssistant, it doesn’t appear to triggered by HA (just says “garage door opened”.)

im using 2.54 mqtt on 2.5i hardware with an S+ 1.0 gdo with an 78LM

**Comment by p-jean** [comment]
This may be related to #33 and #27

**Comment by llamafilm** [comment]
@preppietechie does the door actually open or do you just see false opening events in the log?  For me it's the latter, as I described here: https://community.home-assistant.io/t/filtering-spurious-quick-changes/659558

I have Liftmaster 8500 (secplus 1.0).  Using v2.51 on hardware version 2.5.
I have an 889LM but I believe that's irrelevant because I see the same issue with it disconnected.
It looks like this may be addressed by 59bed215463c600f66652e4b861ac4b770fdc92f so I'm going to try updating to v2.56 now and see if that helps.

**Comment by preppietechie** [comment]
I actually see the door open. I had to put in a band-aid via home assistant that closes the door if it open overnight.

**Comment by PaulWieland** [comment]
Upgrade to latest firmware and make sure your broker isn't spamming mqtt messages to ratgdo for some reason.

**Comment by preppietechie** [comment]
Upgraded to the latest firmware. Things seemed fine for about a week, however, just now I had a random door open event. 

I'm running the Mosquito broker add-on for HomeAssistant, and don't see anything interesting in the logs. Possible feature request: a log on the RatGDO admin page that shows what initiated a door open/close (the wall button, the MQTT source, the antenna, etc). I'm unsure of how to check to make sure the broker isn't sending out a lot of mqtt messages.
